Module3 task1
htmlacademy-react/1343543-what-to-watch-5 pull request #5
Opened 2020-10-08 10:11 UTC by dmitrykhalimov

Очень странно сформулировано домашнее задание – совершенно непонятно, то ли я сделал :/ Да и вообще, ощущение полного бардака в проекте. Несколько issues

1. Элемент Button с точки зрения семантики не верно преобразовывать в Link (или оборачивать им), использовал проп history. При этом, history если использовать метод Route рекомендованный в документации, в пропсах не передается. 
Пришлось в роутере переписать рендер Film на метод Router render (что мне кажется жестким колхозанством, т.к. он согласно документации оставлен «для поддержки»), но как сделать лучше – не знаю. Попробовал объявить history в самом компоненте Film (import history + const history = createBrowserHistory()), переход работает, но роутер – нет.
Чешется рука правда button в принципе поменять на link.

2. При клике на карточке используется Link, который открывает страницу фильма. И если строка в адресной строке верная, то отрисовывается все равно фильм с индексом[0], т.к. в роутере, в Film передаю один мок films[0]. ДЗ о необходимости настройки точной маршрутизации умалчивает. Можно научить компонент брать индекс из адресной строки и передавать в роутере в Film его, но мне кажется странным завязываться на адресную строку.

2020-10-08 12:41 UTC, balesniy commented
> Очень странно сформулировано домашнее задание – совершенно непонятно, то ли я сделал :/ Да и вообще, ощущение полного бардака в проекте. 

это задание про передачу данных в компоненты, роутер нам сейчас нужен только для отладки

>    Чешется рука правда button в принципе поменять на link.

если там переход по url, то это точно ссылка


> Можно научить компонент брать индекс из адресной строки и передавать в роутере в Film его, но мне кажется странным завязываться на адресную строку.

так мы дальше будем делать

2020-10-08 13:13 UTC, balesniy requested changes
посмотри статью https://goshakkk.name/controlled-vs-uncontrolled-inputs-react/ в форме нужно определиться с подходом

2020-10-08 13:13 UTC, balesniy commented on src/components/form-review/form-review.jsx
> +                    // TODO: хотелось добавить тернарный оператор {mark === 3 ? defaultChecked : ``), чтобы 3 звезды стояли по умолчанию но JSX в упор не понимает такую конструкцию. Надо будет пофикс
ага, помни что пропс это не настоящие атрибуты, а просто поля в объекте, `defaultChecked={mark === 3}` но вообще он нужен для неуправляемого компонента, а у тебя rating в состоянии, значит нужно явно каждому инпуту проставить checked

2020-10-08 13:13 UTC, balesniy commented on src/components/form-review/form-review.jsx
> +            <textarea className="add-review__textarea" name="review-text" id="review-text" placeholder="Review text" onChange={this.handleCommentChange}></textarea>
для onChange + state нужен value

2020-10-08 13:13 UTC, balesniy commented on src/components/my-list/my-list.jsx
> +              handleHover = {() => {
Колбэки, переданные в props названы через on

2020-10-08 13:13 UTC, balesniy commented on src/components/player/player.jsx
> +Player.propTypes = {
Д9

2020-10-08 13:13 UTC, balesniy commented on src/const.js
> +    'Very good': 9.9
в константах надежнее будет задать "четкие" границы а в компонентах использовать нестрогие сравнения

2020-10-08 13:13 UTC, balesniy commented on src/mocks/films.js
> +      rankNumber: rank,
тут скорее будет число а не строка

2020-10-08 13:13 UTC, balesniy commented on src/mocks/reviews.js
> +    comments.push({
похоже на map

2020-10-08 13:13 UTC, balesniy commented on src/utils/common.js
> +  for (const ratingRank of ratingRanks) {
а тут похоже на find

2020-10-08 13:13 UTC, balesniy commented on src/utils/common.js
> +    if (rating <= Object.values(ratingRank)) {
Object.values вернет массив

2020-10-08 17:22 UTC, dmitrykhalimov commented
> посмотри статью https://goshakkk.name/controlled-vs-uncontrolled-inputs-react/ в форме нужно определиться с подходом

Спасибо! Посмотрел. Думаю, раз управляемые компоненты - React way, буду использовать их.

2020-10-08 17:31 UTC, dmitrykhalimov commented on src/components/film/film.jsx
> +                    handlePlay(film.id);
Исправлено, заменено на onPlayClick

2020-10-08 17:32 UTC, dmitrykhalimov commented on src/components/film/film.jsx
> +Film.propTypes = {
Упс. Исправил.

2020-10-08 17:42 UTC, dmitrykhalimov commented on src/components/films-list/films-list.jsx
> +      elements.push(<SmallFilmCard key = {films[i].id} preview = {films[i].preview} title = {films[i].title} id = {films[i].id} handleHover= {this.handleHover}/>);
Заменено на map

2020-10-08 17:48 UTC, dmitrykhalimov commented on src/components/form-review/form-review.jsx
> +    // есть большие сомнения что стейт нужно поместить именно на этом уровне, а не на уровне страницы AddReview, или даже табы Reviews, но т.к. неясна архитектура и дальнейшая логика оставил здесь
Принято! :)

2020-10-08 17:48 UTC, dmitrykhalimov commented on src/components/form-review/form-review.jsx
> +      rating: 5,
:( Исправил.

2020-10-08 17:50 UTC, dmitrykhalimov commented on src/components/form-review/form-review.jsx
> +  // не очень понятно зачем вешать onChange на текстовое поле, но так было в демонстрации к лекции :/
Принято! Про управляемые и неуправляемые компоненты нам чего-то не рассказали :(

2020-10-08 18:02 UTC, dmitrykhalimov commented on src/components/form-review/form-review.jsx
> +            <textarea className="add-review__textarea" name="review-text" id="review-text" placeholder="Review text" onChange={this.handleCommentChange}></textarea>
Исправлено, добавлен value={this.state.comment}

2020-10-08 18:04 UTC, dmitrykhalimov commented on src/components/my-list/my-list.jsx
> +              handleHover = {() => {
Исправлено

2020-10-08 18:04 UTC, dmitrykhalimov commented on src/components/player/player.jsx
> +Player.propTypes = {
Исправлено

2020-10-08 18:06 UTC, dmitrykhalimov commented on src/mocks/films.js
> +      rankNumber: rank,
Да, там как раз rank = Number(`${getRandomInteger(1, 9)}.${getRandomInteger(1, 9)}`) - передается :)

2020-10-08 20:21 UTC, dmitrykhalimov commented on src/mocks/reviews.js
> +    comments.push({
Исправлено на map.

2020-10-09 11:35 UTC, dmitrykhalimov commented on src/utils/common.js
> +    if (rating <= Object.values(ratingRank)) {
И ведь работало же :))))))

2020-10-09 11:36 UTC, dmitrykhalimov commented on src/utils/common.js
> +  for (const ratingRank of ratingRanks) {
Исправлено, заменено на find.

2020-10-09 11:36 UTC, dmitrykhalimov commented on src/const.js
> +    'Very good': 9.9
Добавил четкие границы

2020-10-09 12:13 UTC, dmitrykhalimov commented on src/components/form-review/form-review.jsx
> +                    // TODO: хотелось добавить тернарный оператор {mark === 3 ? defaultChecked : ``), чтобы 3 звезды стояли по умолчанию но JSX в упор не понимает такую конструкцию. Надо будет пофикс
Исправлено

2020-10-09 12:18 UTC, dmitrykhalimov commented
> > Очень странно сформулировано домашнее задание – совершенно непонятно, то ли я сделал :/ Да и вообще, ощущение полного бардака в проекте.
> 
> это задание про передачу данных в компоненты, роутер нам сейчас нужен только для отладки
> 
> > Чешется рука правда button в принципе поменять на link.
> 
> если там переход по url, то это точно ссылка
> 
> > Можно научить компонент брать индекс из адресной строки и передавать в роутере в Film его, но мне кажется странным завязываться на адресную строку.
> 
> так мы дальше будем делать

Спасибо, про кнопку понял. Действительно, ее можно без изменений css заменить на Link. Сделаю в следующем ДЗ а то вдруг history.push зачем-нибудь понадобится? :)

2020-10-09 12:29 UTC, dmitrykhalimov commented on src/components/form-review/form-review.jsx
> +    // отправить на сервер state
Предусмотрел колбек :)

2020-10-10 07:47 UTC, balesniy approved these changes

2020-10-10 07:47 UTC, balesniy commented on src/components/films-list/films-list.jsx
> +  onFilmCardHover(id) {
Д3. Методы-обработчики классов названы через handle

2020-10-10 07:47 UTC, merged