Module4 task1
htmlacademy-react/1343543-what-to-watch-5 pull request #6
Opened 2020-10-15 10:36 UTC by dmitrykhalimov

Голову себе сломал об этом задание: как-то у меня очень просто получилось, и меня это смущает. Даже посмотрел мельком чужие ДЗ – там чего-то такого нагорожено: хоки, проброс стейтов, и смутился еще больше.

У меня все как трактор: видеоплеер принимает пропсы, по наведению при помощи рефа плеер играет, по уходу курсора плеер не играет. Все. И перерисовывать ничего не надо.

Но чую где-то подвох  :/ Пока не стал изменять компоненты small-movie-card и flims-list (там стейт activefilm - лишний, и лишние методы), вдруг я все-таки переупростил.

2020-10-15 14:27 UTC, balesniy requested changes

2020-10-15 14:27 UTC, balesniy commented on src/components/small-movie-card/smaill-movie-card.jsx
>  const SmallFilmCard = (props) => {
Б36. Название файла совпадает с названием экпортируемого модуля.

2020-10-15 14:27 UTC, balesniy commented on src/components/video-player/video-player.jsx
> +    if (this.filmTimeout) {
плеер завернут в Link, чтобы при клике сбросить таймер, тут еще понадобится willUnmount

2020-10-15 14:27 UTC, balesniy commented on src/components/films-list/films-list.jsx
> +  handleFilmCardHover(id) {
в твоем решении эта функциональность получилась лишней, можно убирать состояние из компонента

2020-10-15 15:55 UTC, dmitrykhalimov commented on src/components/small-movie-card/smaill-movie-card.jsx
>  const SmallFilmCard = (props) => {
Исправлено

2020-10-15 16:09 UTC, dmitrykhalimov commented on src/components/video-player/video-player.jsx
> +    if (this.filmTimeout) {
Исправлено

2020-10-15 21:01 UTC, balesniy commented on src/components/video-player/video-player copy.jsx
> +class VideoPlayer extends PureComponent {
похоже пуш не прошел, копия плеера сейчас лишняя, но возможно пригодится для полноэкранного

2020-10-16 07:21 UTC, dmitrykhalimov commented on src/components/video-player/video-player copy.jsx
> +class VideoPlayer extends PureComponent {
Извини :( Вместо push отправил pull и ушел смотреть лекцию...

Лишний видеоплеер - удалял, но теперь вернул назад :)

2020-10-16 07:40 UTC, merged